<footer>
    <div class="clear"></div>
    <div id="copyright">© Florian MORENO - TEAM ROCKET</div></br>
    <div id="workTeam">
        <div>
            <h6 class="text-center">CHEF DE PROJET</h6>
            <p class="text-center">Pierre MARQUET</p>
        </div>

        <div>
            <h6 class="text-center">DEVELOPPEURS</h6>
            <p id="dev" class="text-center"><span>Florian MORENO</span> <span class="toHidden">-</span> <span>Pierre MARQUET</span> <span class="toHidden">-</span> <span>Alexis GARANDEAU</span> <span class="toHidden">-</span> <span>Loïc MORIN</span> <span class="toHidden">-</span> <span>Thomas FIORINA</span></p>
        </div>

        <div>
            <a class="toHidden" href="https://www.facebook.com/groups/317800748386555" onclick="window.open(this.href); return false;"><img src="/TeamRocket/Img/Src/facebook.png" alt=""></a>
        </div>
    </div>

</footer>