<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/TeamRocket/Library/css/style.css">
    <link rel="icon" href="/TeamRocket/Img/Src/favicon.ico" />
    <title>Team Rocket - Accueil</title>
</head>

<body>

    <?php include_once 'View/Include/header.phtml'; ?>

    <?php include_once 'View/Include/nav.phtml'; ?>

    <main class="container-fluid">

        <div id="presentation">

            <h2>Présentation</h2>

            <p>C'est en 2015 que l'association TEAM ROCKET voit le jour. Elle est née de l'envie d'un groupe d'amis de créer une équipe de football à sept.
                Nous sommes inscrits au championnat de la FSGT, avec pour volonté de monter de "poule" au fil des saisons sans pour autant mettre de coté la bonne humeur.
                Nous recherchons sans cesse de nouveaux joueurs qui souhaiteraient nous rejoindre afin de compléter l'effectif et ajouter du "sang neuf".
                N'hésitez pas à jeter un coup d'œil au site.</p>

        </div>

        <div id="home">

            <section>

                <div id="listhome" class="matchHome">

                    <h2>Liste des matchs</h2>

                    <form action="index.php?#listhome" method="post" id="seasonForm" class="form-inline justify-content-center">
                        <label for="Season" class="col-form-label mb-2 mr-sm-2">Saison</label>
                        <select name="Season" class="form-control mb-2 mr-sm-2">
                            <?php for ($season = 2019; $season < (date("Y") + 2); $season++) : ?>
                                <option value="<?= $season ?>/<?= $season + 1 ?>" <?php if (isset($_POST['Season']) && $_POST['Season'] == $season . "/" . ($season + 1)) echo 'selected'; ?>><?= $season ?>/<?= $season + 1 ?></option>
                            <?php endfor ?>
                        </select>

                        <input type="submit" value="Valider" class="btn btn-primary mb-2 mr-sm-2">
                    </form>

                    <table>
                        <tr class="toHidden">
                            <th>Date et Heure</th>
                            <th>Equipe adverse</th>
                            <th class="stadiumAdress">Stade et adresse</th>
                            <th class="commentary">Commentaire</th>
                            <th class="tButton"></th>
                        </tr>

                        <?php foreach ($list as $match) : ?>

                            <tr>
                                <td><?= $match['trueDate']; ?> à <?= $match['Heure']; ?> </td>
                                <td><?= $match['Nom_equipe']; ?> </td>
                                <td class="stadiumAdress"><?= $match['Nom_stade']; ?> - <?= $match['Adresse']; ?></td>
                                <td class="commentary"> <?= $match['Commentaires']; ?> </td>
                                <td class="tButton">

                                    <?php if (isset($_SESSION['PlayerID']) && isset($_SESSION['Position'])) : ?>

                                        <?php if (date("Y-m-d") > $match['Date']) : ?>

                                            <input type="submit" value="Terminé" class="btn btn-dark btn-sm  tableBtn" disabled />

                                        <?php elseif ($match['inscrit'] == 1) : ?>

                                            <form action="index.php?matchUnsubscribe" method="post">
                                                <input type="hidden" name="IdMatch" value="<?= $match['Id_match'] ?>" />
                                                <input type="hidden" name="IdPlayer" value="<?= $_SESSION['PlayerID'] ?>" />
                                                <input type="hidden" name="IdRivalteam" value="<?= $match['Id_equipe_adverse'] ?>" />
                                                <input type="submit" value="Désinscription" class="btn btn-danger btn-sm tableBtn " onclick="if (window.confirm('Vous êtes sûr ?')) {return true;} else {return false;}" />
                                            </form>

                                        <?php else : ?>

                                            <form action="index.php?matchRegistration" method="post">
                                                <select name="Position" class="form-control input-sm">
                                                    <option value="Attaquant" <?php if ($_SESSION['Position'] == "Attaquant") echo 'selected'; ?>>Attaquant</option>
                                                    <option value="Milieu" <?php if ($_SESSION['Position'] == "Milieu") echo 'selected'; ?>>Milieu</option>
                                                    <option value="Défenseur" <?php if ($_SESSION['Position'] == "Défenseur") echo 'selected'; ?>>Défenseur</option>
                                                    <option value="Gardien" <?php if ($_SESSION['Position'] == "Gardien") echo 'selected'; ?>>Gardien</option>
                                                </select>
                                                <input type="hidden" name="IdMatch" value="<?= $match['Id_match'] ?>" />
                                                <input type="hidden" name="IdPlayer" value="<?= $_SESSION['PlayerID'] ?>" />
                                                <input type="hidden" name="IdRivalteam" value="<?= $match['Id_equipe_adverse'] ?>" />
                                                <input type="submit" value="Inscription" class="btn btn-primary btn-sm tableBtn" />
                                            </form>

                                        <?php endif ?>

                                    <?php endif ?>

                                </td>
                            </tr>
                        <?php endforeach ?>

                        <tr class="toHidden">
                            <th>Date et Heure</th>
                            <th>Equipe adverse</th>
                            <th class="stadiumAdress">Stade et adresse</th>
                            <th class="commentary">Commentaire</th>
                            <th class="tButton"></th>
                        </tr>

                    </table>
                </div>

            </section>

            <aside>
                <div>
                    <script charset='UTF-8' src='http://www.meteofrance.com/mf3-rpc-portlet/rest/vignettepartenaire/315550/type/VILLE_FRANCE/size/PORTRAIT_VIGNETTE' type='text/javascript'></script>
                </div>
                <div>
                    <iframe src="http://winky.fr/winky_widget_calendar/?wid=0" style="width: 150px; height: 200px; border: none;"></iframe>
                </div>
            </aside>
        </div>
    </main>

    <?php include_once 'View/Include/footer.phtml'; ?>

</body>

</html>