<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/TeamRocket/Library/css/style.css">
    <link rel="icon" href="/TeamRocket/Img/Src/favicon.ico" />
    <title>Team Rocket - Top 10 des Buts</title>
</head>

<body>

    <?php include_once 'View/Include/header.phtml'; ?>

    <?php include_once 'View/Include/nav.phtml'; ?>

    <main class="container-fluid">

        <div id="list" class="topGoalList">

            <h2>Top 10 des joueurs</h2>

            <form action="#" method="post" id="topForm" class="form-inline justify-content-center">
                <select name="TopList" class="form-control  mb-2 mr-sm-2">
                    <option value="TopGoal">Top Buts</option>
                    <option value="TopAssist" <?php if (isset($_POST['TopList']) and $_POST['TopList'] == "TopAssist") echo 'selected' ?>>Top Passes décisives</option>
                    <option value="TopTime" <?php if (isset($_POST['TopList']) and $_POST['TopList']  == "TopTime") echo 'selected' ?>>Top Temps de jeu</option>
                    <option value="TopPresence" <?php if (isset($_POST['TopList']) and $_POST['TopList'] == "TopPresence") echo 'selected' ?>>Top Présence</option>
                </select>

                <select name="Season" class="form-control  mb-2 mr-sm-2">
                    <?php for ($season = 2019; $season < (date("Y") + 2); $season++) : ?>
                        <option value="<?= $season ?>/<?= $season + 1 ?>" <?php if (isset($_POST['Season']) && $_POST['Season'] == $season . "/" . ($season + 1)) echo 'selected'; ?>><?= $season ?>/<?= $season + 1 ?></option>
                    <?php endfor ?>
                </select>

                <input type="submit" value="Valider" class="btn btn-primary  mb-2 mr-sm-2">
            </form>

            <table>
                <tr class="toHidden">
                    <th class="ranking">Classement</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <?php if (isset($_POST['TopList']) and $_POST['TopList'] == "TopAssist") : ?>
                        <th>Total de passes décisives</th>
                    <?php elseif (isset($_POST['TopList']) and $_POST['TopList'] == "TopTime") : ?>
                        <th>Total de temps de jeu</th>
                    <?php elseif (isset($_POST['TopList']) and $_POST['TopList'] == "TopPresence") : ?>
                        <th>Total de participation</th>
                    <?php else : ?>
                        <th>Total des buts</th>
                    <?php endif ?>
                </tr>

                <?php foreach ($list as $player) : ?>

                    <tr>
                        <td class="ranking"><?= $ranking++ ?>e</td>
                        <td><?= $player['Nom']; ?></td>
                        <td><?= $player['Prenom']; ?></td>
                        <?php if (isset($player['passes_totale'])) : ?>
                            <td><?= $player['passes_totale']; ?></td>
                        <?php elseif (isset($player['temps_total'])) : ?>
                            <td><?= $player['temps_total']; ?></td>
                        <?php elseif (isset($player['presence'])) : ?>
                            <td><?= $player['presence']; ?></td>
                        <?php else : ?>
                            <td><?= $player['buts_totaux']; ?> </td>
                        <?php endif ?>
                    </tr>

                <?php endforeach ?>

                <tr class="toHidden">
                    <th class="ranking">Classement</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <?php if (isset($_POST['TopList']) and $_POST['TopList'] == "TopAssist") : ?>
                        <th>Total de passes décisives</th>
                    <?php elseif (isset($_POST['TopList']) and $_POST['TopList'] == "TopTime") : ?>
                        <th>Total de temps de jeu</th>
                    <?php elseif (isset($_POST['TopList']) and $_POST['TopList'] == "TopPresence") : ?>
                        <th>Total de participation</th>
                    <?php else : ?>
                        <th>Total des buts</th>
                    <?php endif ?>
                </tr>
            </table>

        </div>
    </main>

    <?php include_once 'View/Include/footer.phtml'; ?>

</body>

</html>