<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/TeamRocket/Library/css/style.css">
    <link rel="icon" href="/TeamRocket/Img/Src/favicon.ico" />
    <title>Team Rocket - Créer un compte</title>
    <script type="text/javascript" src="/TeamRocket/Library/js/validUserForm.js"></script>
</head>

<body>

    <?php include_once 'View/Include/header.phtml'; ?>

    <?php include_once 'View/Include/nav.phtml'; ?>

    <main class="container-fluid">

        <form id="form" action="index.php?addUser" enctype="multipart/form-data" method="POST" required>

            <legend>Formulaire d'inscription</legend>
            <div id="innerForm">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="Lastname">Nom <span class="star">*</span></label>
                        <input type="text" name="Lastname" id="Lastname" class="form-control" pattern="^[A-Za-zÀ-ÿ ]{2,25}" required>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="Firstname">Prénom <span class="star">*</span></label>
                        <input type="text" name="Firstname" id="Firstname" class="form-control" pattern="^[A-Za-zÀ-ÿ ]{2,25}" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="PseudoUser">Pseudo <span class="star">*</span></label>
                        <input type="text" name="PseudoUser" id="PseudoUser" class="form-control" pattern="[A-Za-z0-9 ]{2,20}" required>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="Mail">Email <span class="star">*</span></label>
                        <input type="email" name="Mail" id="Mail" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="PasswordUser">Mot de passe <span class="star">*</span></label>
                        <input type="password" name="PasswordUser" id="PasswordUser" class="form-control" pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$" placeholder="Au moins 1 majuscule, 1 minuscule et 1 nombre" required>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="PasswordValid">Confirmer le mot de passe <span class="star">*</span></label>
                        <input type="password" name="PasswordValid" id="PasswordValid" class="form-control" pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$" placeholder="Au moins 1 majuscule, 1 minuscule et 1 nombre" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="ArrivalYear">Année d'arrivée</label>
                        <input type="date" name="ArrivalYear" id="ArrivalYear" class="form-control">
                    </div>

                    <div class="form-group col-md-6">
                        <label for="LicenseNumber">N° de Licence</label>
                        <input type="number" name="LicenseNumber" id="LicenseNumber" class="form-control" min="0" max="9999999999">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <input type="hidden" name="MAX_FILE_SIZE" value="10000000" />
                        <label for="Picture">Photo de profil</label>
                        <input type="file" id="Picture" class="form-control" name="Picture" accept="image/png, image/jpeg">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="Position">Poste souhaité</label>
                        <select name="Position" class="form-control">
                            <option value="Attaquant" selected>Attaquant</option>
                            <option value="Milieu">Milieu</option>
                            <option value="Défenseur">Défenseur</option>
                            <option value="Gardien">Gardien</option>
                        </select>
                    </div>
                </div>

                <div class="form-group text-center">
                    <p>les champs <span class="star">*</span> sont obligatoires</p>
                    <?php if (isset($_SESSION['error'])) : ?>
                        <p class="error">Attention : <?php echo $_SESSION['error'];  ?></p>
                        <?php $_SESSION['error'] = null;  ?>
                    <?php endif ?>
                    <p class="errorField"></p>
                    <p class="errorPicture"></p>
                </div>

                <div class="form-group text-center">
                    <div id="valiForm">
                        <input type="submit" value="Créer" class="btn btn-primary buttonCustom">
                        <a href="index.php?userList" class="btn btn-primary buttonCustom">Retour</a>
                    </div>
                </div>
            </div>
        </form>

    </main>

    <?php include_once 'View/Include/footer.phtml'; ?>

</body>

</html>