<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/TeamRocket/Library/css/style.css">
    <link rel="icon" href="/TeamRocket/Img/Src/favicon.ico" />
    <title>Team Rocket - Liste des matchs</title>
</head>

<body>

    <?php include_once 'View/Include/header.phtml'; ?>

    <?php include_once 'View/Include/nav.phtml'; ?>

    <main class="container-fluid">

        <div id="list" class="matchList">

            <h2>Liste des matchs</h2>

            <a href="index.php?formAddmatch" class="btn btn-primary btn-lg">Ajouter un Match</a>

            <table>
                <tr class="toHidden">
                    <th>Date et Heure</th>
                    <th>Saison</th>
                    <th>Equipe adverse</th>
                    <th>Stade</th>
                    <th class="tButton" colspan="3"></th>
                </tr>

                <?php foreach ($list as $match) : ?>
                    <tr>
                        <td> <?= $match['trueDate']; ?> à <?= $match['Heure']; ?> </td>
                        <td> <?= $match['Saison'] ?> </td>
                        <td> <?= $match['Nom_equipe']; ?> </td>
                        <td> <?= $match['Nom_stade']; ?> </td>
                        <td class="tButton">
                            <form action="index.php?playerRegistration" method="post">
                                <input type="hidden" name="Idmatch" value="<?= $match['Id_match'] ?>" />
                                <input type="submit" value="Inscrits" class="btn btn-dark btn-sm tableBtn" />
                            </form>
                        </td>
                        <td class="tButton">
                            <form action="index.php?formModifymatch" method="post">
                                <input type="hidden" name="Idmatch" value="<?= $match['Id_match'] ?>" />
                                <input type="submit" value="Modifier" class="btn btn-primary btn-sm tableBtn" />
                            </form>
                        </td>
                        <td class="tButton">
                            <form action="index.php?deletematch" method="post">
                                <input type="hidden" name="Idmatch" value="<?= $match['Id_match'] ?>" />
                                <input type="submit" value="Supprimer" onclick="if (window.confirm('Vous êtes sûr ?')) {return true;} else {return false;}" 
                                class="btn btn-danger btn-sm tableBtn" />
                            </form>
                        </td>
                    </tr>
                <?php endforeach ?>

                <tr class="toHidden">
                    <th>Heure</th>
                    <th>Date</th>
                    <th>Equipe adverse</th>
                    <th>Stade</th>
                    <th class="tButton" colspan="3"></th>
                </tr>

            </table>

            <a href="index.php?formAddmatch" class="btn btn-primary btn-lg">Ajouter un Match</a>

        </div>
    </main>

    <?php include_once 'View/Include/footer.phtml'; ?>

</body>

</html>
